// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {main} from '../models';

export function AddHistoryEntry(arg1:core.HistoryEntry):Promise<void>;

export function BufferLabels():Promise<Array<string>>;

export function CalculateChecksum(arg1:string):Promise<core.ChecksumResult>;

export function CancelOperation():Promise<void>;

export function CheckDiskSpace(arg1:string):Promise<core.DiskSpaceInfo>;

export function ChunkLabels():Promise<Array<string>>;

export function ClearHistory():Promise<void>;

export function DetectParts(arg1:string):Promise<main.DetectResult>;

export function FormatSize(arg1:number):Promise<string>;

export function GetFileInfo(arg1:string):Promise<main.FileInfo>;

export function GetHistory():Promise<Array<core.HistoryEntry>>;

export function InspectPKG(arg1:string):Promise<core.PKGInfo>;

export function LoadConfig():Promise<core.Config>;

export function MergeFiles(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenFilesDialog():Promise<Array<string>>;

export function RenamePKG(arg1:string):Promise<string>;

export function SaveConfig(arg1:core.Config):Promise<void>;

export function SplitFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SplitFormatLabels():Promise<Array<string>>;

export function SuggestOutputPath(arg1:Array<string>,arg2:string):Promise<string>;

export function SuggestRenamePKG(arg1:string):Promise<main.RenameResult>;

export function ValidatePKG(arg1:string):Promise<main.ValidationResult>;
