// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistoryEntry(arg1) {
  return window['go']['main']['App']['AddHistoryEntry'](arg1);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function BufferLabels() {
  return window['go']['main']['App']['BufferLabels']();
}

export function CalculateChecksum(arg1) {
  return window['go']['main']['App']['CalculateChecksum'](arg1);
}

export function CancelOperation() {
  return window['go']['main']['App']['CancelOperation']();
}

export function CheckDiskSpace(arg1) {
  return window['go']['main']['App']['CheckDiskSpace'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ChunkLabels() {
  return window['go']['main']['App']['ChunkLabels']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ConfigureUpdateOnStartup(arg1) {
  return window['go']['main']['App']['ConfigureUpdateOnStartup'](arg1);
}

export function CreatePS1FPKG(arg1) {
  return window['go']['main']['App']['CreatePS1FPKG'](arg1);
}

export function CreatePS2FPKG(arg1) {
  return window['go']['main']['App']['CreatePS2FPKG'](arg1);
}

export function DetectDiscType(arg1) {
  return window['go']['main']['App']['DetectDiscType'](arg1);
}

export function DetectPS1Disc(arg1) {
  return window['go']['main']['App']['DetectPS1Disc'](arg1);
}

export function DetectPS2Disc(arg1) {
  return window['go']['main']['App']['DetectPS2Disc'](arg1);
}

export function DetectParts(arg1) {
  return window['go']['main']['App']['DetectParts'](arg1);
}

export function DownloadAndApplyUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndApplyUpdate'](arg1);
}

export function FormatSize(arg1) {
  return window['go']['main']['App']['FormatSize'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function InspectPKG(arg1) {
  return window['go']['main']['App']['InspectPKG'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function MergeFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['MergeFiles'](arg1, arg2, arg3);
}

export function OpenCUEFileDialog() {
  return window['go']['main']['App']['OpenCUEFileDialog']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenEmulatorDirDialog() {
  return window['go']['main']['App']['OpenEmulatorDirDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFilesDialog() {
  return window['go']['main']['App']['OpenFilesDialog']();
}

export function OpenISOFileDialog() {
  return window['go']['main']['App']['OpenISOFileDialog']();
}

export function OpenImageFileDialog(arg1) {
  return window['go']['main']['App']['OpenImageFileDialog'](arg1);
}

export function RenamePKG(arg1) {
  return window['go']['main']['App']['RenamePKG'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SavePKGFileDialog(arg1) {
  return window['go']['main']['App']['SavePKGFileDialog'](arg1);
}

export function SplitFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SplitFile'](arg1, arg2, arg3, arg4, arg5);
}

export function SplitFormatLabels() {
  return window['go']['main']['App']['SplitFormatLabels']();
}

export function SuggestOutputPath(arg1, arg2) {
  return window['go']['main']['App']['SuggestOutputPath'](arg1, arg2);
}

export function SuggestRenamePKG(arg1) {
  return window['go']['main']['App']['SuggestRenamePKG'](arg1);
}

export function UpdateBackend() {
  return window['go']['main']['App']['UpdateBackend']();
}

export function ValidatePKG(arg1) {
  return window['go']['main']['App']['ValidatePKG'](arg1);
}
