// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistoryEntry(arg1) {
  return window['go']['main']['App']['AddHistoryEntry'](arg1);
}

export function BufferLabels() {
  return window['go']['main']['App']['BufferLabels']();
}

export function CalculateChecksum(arg1) {
  return window['go']['main']['App']['CalculateChecksum'](arg1);
}

export function CancelOperation() {
  return window['go']['main']['App']['CancelOperation']();
}

export function CheckDiskSpace(arg1) {
  return window['go']['main']['App']['CheckDiskSpace'](arg1);
}

export function ChunkLabels() {
  return window['go']['main']['App']['ChunkLabels']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DetectParts(arg1) {
  return window['go']['main']['App']['DetectParts'](arg1);
}

export function FormatSize(arg1) {
  return window['go']['main']['App']['FormatSize'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function InspectPKG(arg1) {
  return window['go']['main']['App']['InspectPKG'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function MergeFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['MergeFiles'](arg1, arg2, arg3);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFilesDialog() {
  return window['go']['main']['App']['OpenFilesDialog']();
}

export function RenamePKG(arg1) {
  return window['go']['main']['App']['RenamePKG'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SplitFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SplitFile'](arg1, arg2, arg3, arg4, arg5);
}

export function SplitFormatLabels() {
  return window['go']['main']['App']['SplitFormatLabels']();
}

export function SuggestOutputPath(arg1, arg2) {
  return window['go']['main']['App']['SuggestOutputPath'](arg1, arg2);
}

export function SuggestRenamePKG(arg1) {
  return window['go']['main']['App']['SuggestRenamePKG'](arg1);
}

export function ValidatePKG(arg1) {
  return window['go']['main']['App']['ValidatePKG'](arg1);
}
